name: Release

on:
    workflow_dispatch:
        inputs:
            tag:
                description: "Tag of pyvroom to release"
                required: true

permissions:
    contents: write

jobs:
    build:
        name: ${{ matrix.platform }}
        runs-on: ${{ matrix.worker }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - worker: [rpi, raw]
                      platform: linux-arm64
                    - worker: [ubuntu-latest]
                      platform: linux-x64

        env:
            TAG: ${{ github.event.inputs.tag }}
        steps:
            - name: Checkout pyvroom
              uses: actions/checkout@v4
              with:
                  repository: "VROOM-Project/pyvroom"
                  submodules: "recursive"
                  ref: ${{ github.event.inputs.tag }}

            - name: Checkout self
              uses: actions/checkout@v4
              with:
                  path: self

            - name: Setup Python
              if: matrix.platform == 'linux-x64'
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11

            - name: Apply patches
              run: |
                  git apply self/patches/*.patch

            - name: Install build dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r build-requirements.txt
                  pip install cibuildwheel

            - name: Build wheels
              run: |
                  python -m cibuildwheel --output-dir wheelhouse

            - name: Upload wheels
              uses: actions/upload-artifact@v4
              with:
                  path: wheelhouse/*.whl

    release:
        name: Release
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: artifact
                  path: dist

            - name: List files
              run: |
                  ls -ahl dist

            - name: Fail for test purposes
              run: |
                  exit 1

            - name: Create release
              uses: softprops/action-gh-release@v2
              with:
                  files: dist/*
                  tag_name: ${{ github.event.inputs.tag }}
                  body: "Release of pyvroom ${{ github.event.inputs.tag }}."
                  name: ${{ github.event.inputs.tag }}
                  fail_on_unmatched_files: true
