name: Release

on:
    workflow_dispatch:
        inputs:
            tag:
                description: "Tag of pyvroom to release"
                required: true

permissions:
    contents: write

jobs:
    build:
        name: ${{ matrix.platform }}
        runs-on: ${{ matrix.worker }}
        strategy:
            fail-fast: true
            matrix:
                include:
                    - worker: ubuntu-latest
                      platform: linux-x64
                    - worker: macos-latest
                      platform: macos-x64
                    - worker: windows-latest
                      platform: windows-x64
                    - worker: rpi
                      platform: linux-arm64

        env:
            TAG: ${{ github.event.inputs.tag }}
        steps:
            - name: Checkout pyvroom
              uses: actions/checkout@v4
              with:
                  repository: "VROOM-Project/pyvroom"
                  submodules: "recursive"
                  ref: ${{ github.event.inputs.tag }}

            - name: Set up Python
              if: ${{ matrix.platform != 'linux-arm64' }} # setup python does not support linux-arm64
              uses: actions/setup-python@v5
              with:
                  python-version: 3.11

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r build-requirements.txt

            - name: Install cibuildwheel
              run: python -m pip install cibuildwheel==2.18.1

            - name: Build wheels
              run: python -m cibuildwheel --output-dir wheelhouse

            - name: Upload wheels
              uses: actions/upload-artifact@v3
              with:
                  path: wheelhouse/*.whl

    publish:
        runs-on: ubuntu-latest
        needs: build
        strategy:
            matrix:
                include:
                    - target-env: pypi
                      target-url: https://pypi.org/p/exvis
                    - target-env: testpypi
                      target-url: https://test.pypi.org/p/exvis
        environment:
            name: ${{ matrix.target-env }}
            url: ${{ matrix.target-url }}
        permissions:
            contents: read
            id-token: write # This is required for trusted publishing to PyPI
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: artifact
                  path: dist

            - name: Publish package distributions to PyPI
              if: ${{ matrix.target-env == 'pypi' }}
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  packages-dir: ./dist

            - name: Publish package distributions to TestPyPI
              if: ${{ matrix.target-env == 'testpypi' }}
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  repository-url: https://test.pypi.org/legacy/
                  packages-dir: ./dist

            - name: Create release
              if: ${{ matrix.target-env == 'pypi' }}
              uses: softprops/action-gh-release@v2
              with:
                  files: dist/*
                  tag_name: ${{ github.event.inputs.tag }}
                  body: "Release of pyvroom ${{ github.event.inputs.tag }}."
                  name: ${{ github.event.inputs.tag }}
                  fail_on_unmatched_files: true
