name: Release

on:
    workflow_dispatch:
        inputs:
            tag:
                description: "Tag of pyvroom to release"
                required: true

permissions:
    contents: write

jobs:
    release:
        runs-on: rpi
        env:
            TAG: ${{ github.event.inputs.tag }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  repository: "VROOM-Project/pyvroom"
                  submodules: "recursive"
                  ref: ${{ github.event.inputs.tag }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r build-requirements.txt

            - name: Build wheel
              run: |
                  pip wheel --no-deps --wheel-dir dist .

            - name: Create release
              uses: softprops/action-gh-release@v2
              with:
                  files: dist/*
                  tag_name: ${{ github.event.inputs.tag }}
                  body: "Release of pyvroom ${{ github.event.inputs.tag }} (linux/arm64)."
                  name: ${{ github.event.inputs.tag }}
                  fail_on_unmatched_files: true
