name: Release

on:
    workflow_dispatch:

jobs:
    release:
        runs-on: rpi
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  repository: "VROOM-Project/pyvroom"
                  submodules: "recursive"
                  ref: "main"

            - name: Set up Python
              uses: deadsnakes/action@v3.1.0
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r build-requirements.txt

            - name: Build wheel
              run: |
                  pip wheel --no-deps --wheel-dir dist .
